[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino

; ---------------------------------------------------------------------------
; Library dependencies
; ---------------------------------------------------------------------------
lib_deps =
    esphome/AsyncTCP-esphome @ ^2.1.3
    esphome/ESPAsyncWebServer-esphome @ ^3.2.2

; ---------------------------------------------------------------------------
; Strip out the hidden default macro, to prevent warning messages when this
; flag is overriden in the build_flags section below.
; ---------------------------------------------------------------------------
build_unflags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1

; ---------------------------------------------------------------------------
; Inject custom configurations. Note that the secrets need single quotes
; around them because they might contain spaces.
; ---------------------------------------------------------------------------
build_flags = 
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=0
    '-D SECRET_WIFI_SSID=${secrets.wifi_ssid}'
    '-D SECRET_WIFI_PASSWORD=${secrets.wifi_pass}'
    '-D SECRET_OTA_PASSWORD=${secrets.ota_pass}'

; ---------------------------------------------------------------------------
; Comment out the upload_* lines below for USB firmware uploads.
; Uncomment them for WiFi firmware uploads. Note that the WiFi firmware
; uploads will not work until after the first USB upload has worked.
; ---------------------------------------------------------------------------
upload_protocol = espota
upload_port = SteamPuckControllerWake.local  
upload_flags =
    --port=3232
    --auth=${secrets.ota_pass}

; ---------------------------------------------------------------------------
; Tell PlatformIO to read your Secrets file to get passwords etc.
; Create a file called "secrets.ini" that looks similar to this:
; 
;     [secrets]
;     wifi_ssid = "Your WiFi Network Name"
;     wifi_pass = "Your WiFi" Network Password"
;     ota_pass = "Your Desired Firmware Update Password"
; 
; Place this "secrets.ini" file in the same folder as this platformio.ini file.
; ---------------------------------------------------------------------------
[platformio]
extra_configs = secrets.ini
